Repository KinsonDigital/Plazma, pull requests merged in 2023-10, with the labels that each got.

#34 🚧Setup json serialization
  Plazma/Behaviors/EasingRandomBehaviorSettings.cs
  Testing/PlazmaTesting/Content/drop.afdesign
Labels: high priority, preview, tech debt

#45 🚀Preview Release (v1.0.0-preview.2)
  Plazma/Plazma.csproj
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
Labels: 🚀Preview Release

#51 🚧Update sync workflow
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, medium priority, preview
