Repository KinsonDigital/Plazma, pull requests merged in 2023-08, with the labels that each got.

#16 🚧Setup cicd and sync system
  .editorconfig
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/triage-issue.yml
  .github/workflows/unit-test-status-check.yml
  .vscode/settings.json
  Plazma.sln
  Plazma.sln.DotSettings
  Plazma/ParticleColor.cs
Labels: ♻️cicd, high priority, ⚙️config

#18 🚧Process all warnings
  Plazma.sln.DotSettings
  Plazma/Behaviors/BehaviorFactory.cs
  Plazma/Behaviors/BehaviorSettings.cs
  Plazma/Behaviors/ColorTransitionBehaviorSettings.cs
  Plazma/Behaviors/EasingRandomBehaviorSettings.cs
  Plazma/Behaviors/IBehaviorFactory.cs
  Plazma/Behaviors/RandomChoiceBehaviorSettings.cs
  Plazma/ExtensionMethods.cs
  Plazma/Particle.cs
  Plazma/ParticleColor.cs
  Plazma/ParticleEffect.cs
  Plazma/ParticleEngine.cs
  Plazma/ParticlePool.cs
  Plazma/Services/ISerializerService.cs
  Plazma/Services/ParticleEffectSerializerService.cs
  Plazma/Services/PseudoRandomizerService.cs
  Plazma/Services/TrueRandomizerService.cs
  Plazma/Version.cs
  Testing/PlazmaTests/Behaviors/BehaviorFactoryTests.cs
  Testing/PlazmaTests/Behaviors/BehaviorSettingsTests.cs
  Testing/PlazmaTests/Behaviors/ColorTransitionBehaviorTests.cs
  Testing/PlazmaTests/Behaviors/EasingRandomBehaviorSettingsTests.cs
  Testing/PlazmaTests/Behaviors/EasingRandomBehaviorTests.cs
  Testing/PlazmaTests/Behaviors/RandomChoiceBehaviorSettingsTests.cs
  Testing/PlazmaTests/Behaviors/RandomColorBehaviorTests.cs
  Testing/PlazmaTests/EasingFunctionsTests.cs
  Testing/PlazmaTests/ExtensionMethodsTests.cs
  Testing/PlazmaTests/Fakes/FakeBehavior.cs
  Testing/PlazmaTests/Fakes/FakeBehaviorSettings.cs
  Testing/PlazmaTests/Fakes/TestItem.cs
  Testing/PlazmaTests/ParticleColorTests.cs
  Testing/PlazmaTests/ParticleEffectTests.cs
  Testing/PlazmaTests/ParticleEngineTests.cs
  Testing/PlazmaTests/ParticlePoolTests.cs
  Testing/PlazmaTests/ParticleTests.cs
  Testing/PlazmaTests/PlazmaTests.csproj
  Testing/PlazmaTests/Services/PseudoRandomizerServiceTests.cs
  Testing/PlazmaTests/Services/TrueRandomizerServiceTests.cs
  Testing/PlazmaTests/XUnitHelpers/AssertExt.cs
  Testing/PlazmaTests/XUnitHelpers/AssertHelpers.cs
Labels: high priority, preview, tech debt

#22 🚧Replace moq code with nsubstitute
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/unit-test-status-check.yml
  Plazma/Particle.cs
  Plazma/ParticleEffect.cs
  Plazma/ParticleEngine.cs
  Plazma/ParticlePool.cs
  Testing/PlazmaTests/Behaviors/BehaviorFactoryTests.cs
  Testing/PlazmaTests/Behaviors/EasingRandomBehaviorTests.cs
  Testing/PlazmaTests/Behaviors/RandomColorBehaviorTests.cs
  Testing/PlazmaTests/ExtensionMethodsTests.cs
  Testing/PlazmaTests/ParticleEffectTests.cs
  Testing/PlazmaTests/ParticleEngineTests.cs
  Testing/PlazmaTests/ParticlePoolTests.cs
  Testing/PlazmaTests/ParticleTests.cs
  Testing/PlazmaTests/PlazmaTests.csproj
  Testing/PlazmaTests/packages.config
Labels: dependency update, high priority

#24 🚧Add manual test project
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/unit-test-status-check.yml
  .run/PlazmaTesting.run.xml
  Plazma.sln
  Plazma/Behaviors/BehaviorFactory.cs
  Plazma/Behaviors/EasingRandomBehavior.cs
  Plazma/Behaviors/EasingRandomBehaviorSettings.cs
  Plazma/Behaviors/Enums.cs
  Plazma/Behaviors/RandomColorBehavior.cs
  Plazma/ExtensionMethods.cs
  Plazma/ITextureLoader.cs
  Plazma/Particle.cs
  Plazma/ParticleEffect.cs
  Plazma/ParticleEngine.cs
  Plazma/ParticlePool.cs
  Plazma/Plazma.csproj
  Testing/PlazmaTesting/Content/Graphics/drop.png
  Testing/PlazmaTesting/Content/drop.afdesign
  Testing/PlazmaTesting/MainWindow.cs
  Testing/PlazmaTesting/ParticleTextureLoader.cs
  Testing/PlazmaTesting/PlazmaTesting.csproj
  Testing/PlazmaTesting/Program.cs
  Testing/PlazmaTesting/Scenes/AngleScene.cs
  Testing/PlazmaTesting/Scenes/ColorScene.cs
  Testing/PlazmaTesting/Scenes/HorizontalMovementScene.cs
  Testing/PlazmaTesting/Scenes/VerticalMovementScene.cs
  Testing/PlazmaTesting/stylecop.json
  Testing/PlazmaTests/Behaviors/BehaviorFactoryTests.cs
  Testing/PlazmaTests/Behaviors/EasingRandomBehaviorSettingsTests.cs
  Testing/PlazmaTests/Behaviors/EasingRandomBehaviorTests.cs
  Testing/PlazmaTests/ExtensionMethodsTests.cs
  Testing/PlazmaTests/ParticleEffectTests.cs
  Testing/PlazmaTests/ParticleEngineTests.cs
  Testing/PlazmaTests/ParticlePoolTests.cs
  Testing/PlazmaTests/ParticleTests.cs
  Testing/PlazmaTests/PlazmaTests.csproj
Labels: medium priority, preview, tech debt

#26 🚧Add new features and improvements
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/unit-test-status-check.yml
  Plazma.sln.DotSettings
  Plazma/Behaviors/Behavior.cs
  Plazma/Behaviors/BehaviorFactory.cs
  Plazma/Behaviors/BehaviorSettings.cs
  Plazma/Behaviors/ColorTransitionBehavior.cs
  Plazma/Behaviors/ColorTransitionBehaviorSettings.cs
  Plazma/Behaviors/EasingRandomBehavior.cs
  Plazma/Behaviors/EasingRandomBehaviorSettings.cs
  Plazma/Behaviors/Enums.cs
  Plazma/Behaviors/IBehavior.cs
  Plazma/Behaviors/IBehaviorFactory.cs
  Plazma/Behaviors/IEasingCapable.cs
  Plazma/Behaviors/RandomChoiceBehaviorSettings.cs
  Plazma/Behaviors/RandomColorBehavior.cs
  Plazma/Enums.cs
  Plazma/Factories/BehaviorFactory.cs
  Plazma/Factories/IBehaviorFactory.cs
  Plazma/Factories/IParticleFactory.cs
  Plazma/Factories/IParticlePoolFactory.cs
  Plazma/Factories/ParticleFactory.cs
  Plazma/Factories/ParticlePoolFactory.cs
  Plazma/IParticle.cs
  Plazma/IParticlePool.cs
  Plazma/ITextureLoader.cs
  Plazma/IoC.cs
  Plazma/Particle.cs
  Plazma/ParticleEffect.cs
  Plazma/ParticleEngine.cs
  Plazma/ParticlePool.cs
  Plazma/Plazma.csproj
  Plazma/Services/TrueRandomizerService.cs
  Testing/PlazmaTesting/MainWindow.cs
  Testing/PlazmaTesting/ParticleTextureLoader.cs
  Testing/PlazmaTesting/PlazmaTesting.csproj
  Testing/PlazmaTesting/Program.cs
  Testing/PlazmaTesting/Scenes/AngleScene.cs
  Testing/PlazmaTesting/Scenes/ColorScene.cs
  Testing/PlazmaTesting/Scenes/HorizontalMovementScene.cs
  Testing/PlazmaTesting/Scenes/VerticalMovementScene.cs
  Testing/PlazmaTests/Behaviors/BehaviorFactoryTests.cs
  Testing/PlazmaTests/Behaviors/BehaviorSettingsTests.cs
  Testing/PlazmaTests/Behaviors/ColorTransitionBehaviorTests.cs
  Testing/PlazmaTests/Behaviors/EasingRandomBehaviorSettingsTests.cs
  Testing/PlazmaTests/Behaviors/EasingRandomBehaviorTests.cs
  Testing/PlazmaTests/Behaviors/RandomChoiceBehaviorSettingsTests.cs
  Testing/PlazmaTests/Behaviors/RandomColorBehaviorTests.cs
  Testing/PlazmaTests/ExtensionMethods.cs
  Testing/PlazmaTests/Fakes/FakeBehaviorSettings.cs
  Testing/PlazmaTests/Fakes/FakeTexture.cs
  Testing/PlazmaTests/ParticleEffectTests.cs
  Testing/PlazmaTests/ParticleEngineTests.cs
  Testing/PlazmaTests/ParticlePoolTests.cs
  Testing/PlazmaTests/ParticleTests.cs
  Testing/PlazmaTests/PlazmaTests.csproj
  Testing/PlazmaTests/Tests.cs
Labels: high priority, preview, tech debt, ✨new feature

#30 🚀Preview Release (v1.0.0-preview.1)
  README.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.1.md
Labels: 🚀Preview Release

#32 🚧Adjust workflow trigger
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, high priority, preview
